version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  bot_network:
    driver: bridge